# Generated by Django 5.2.17 on 2026-09-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField(db_index=True, verbose_name='照护日期')),
                ('title', models.CharField(max_length=128)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '照护计划',
                'ordering': ['-care_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('discipline', models.CharField(choices=[('care', '护理'), ('nutrition', '营养'), ('rehab', '康复'), ('psych', '心理支持')], max_length=16)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False, help_text='可选项：产妇可自行选择是否接受')),
                ('state', models.CharField(choices=[('PROPOSED', '待确认'), ('CONFIRMED', '已确认'), ('PAUSED', '已暂停'), ('IN_CONFLICT', '会商中'), ('REFUSED', '已拒绝')], default='PROPOSED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care.plan')),
            ],
            options={
                'verbose_name': '计划项目',
                'ordering': ['scheduled_time', 'code'],
                'unique_together': {('plan', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(help_text='发布时计划的修订号')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='care.plan')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
                'unique_together': {('plan', 'number')},
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='care.planversion'),
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='care.planitem')),
                ('plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='care.planversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=16)),
                ('opinion_type', models.CharField(choices=[('ASSESSMENT', '评估'), ('RECOMMENDATION', '建议'), ('CONTRAINDICATION', '禁忌'), ('FEEDBACK', '执行反馈'), ('CONFIRMATION', '恢复确认')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='care.planitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='care.plan')),
            ],
            options={
                'verbose_name': '专业意见',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_decision', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', '待会商'), ('RESOLVED', '已决定')], default='OPEN', max_length=12)),
                ('decision', models.CharField(blank=True, choices=[('PROCEED', '会商后恢复执行'), ('HALT', '会商后维持暂停')], max_length=12)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='care.plan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='care.planitem')),
                ('opinions', models.ManyToManyField(related_name='issues', to='care.professionalopinion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_PLAN', '建立计划'), ('ADD_ITEM', '新增项目'), ('OPINION', '提交专业意见'), ('PAUSE', '暂停项目'), ('RESUME', '恢复项目'), ('REFUSE', '产妇拒绝'), ('SELECT', '产妇选择'), ('COMPLETE', '完成记录'), ('PUBLISH', '发布版本'), ('CONFLICT_OPEN', '进入会商'), ('RESOLVE', '会商决定')], max_length=16)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='care.plan')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='care.planitem')),
                ('opinion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='care.professionalopinion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('NURSE', '护理'), ('NUTRITIONIST', '营养'), ('REHABILITATOR', '康复'), ('PSYCHOLOGIST', '心理支持'), ('SUPERVISOR', '服务主管'), ('MOTHER', '产妇')], max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '人员档案',
            },
        ),
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(blank=True, help_text='拒绝范围，如当日、该项目全程', max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refusal', to='care.planitem')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refusals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to='care.professionalopinion')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_events', to='care.planitem')),
                ('resumed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PauseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cleared_pauses', to=settings.AUTH_USER_MODEL)),
                ('paused_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pause_events', to='care.planitem')),
                ('reason_opinion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to='care.professionalopinion')),
                ('resume_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared', to='care.resumeevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('discipline', models.CharField(max_length=16)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('optional', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('PROPOSED', '待确认'), ('CONFIRMED', '已确认'), ('PAUSED', '已暂停'), ('IN_CONFLICT', '会商中'), ('REFUSED', '已拒绝')], max_length=16)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_snapshots', to='care.planitem')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care.planversion')),
            ],
            options={
                'ordering': ['scheduled_time', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VersionOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128)),
                ('discipline', models.CharField(max_length=16)),
                ('opinion_type', models.CharField(choices=[('ASSESSMENT', '评估'), ('RECOMMENDATION', '建议'), ('CONTRAINDICATION', '禁忌'), ('FEEDBACK', '执行反馈'), ('CONFIRMATION', '恢复确认')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_bindings', to='care.professionalopinion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinion_bindings', to='care.planversion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('mother', 'care_date')},
        ),
    ]
