# Generated by Django 5.2.17 on 2026-09-19 08:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('MOTHER', '产妇'), ('NURSE', '护理人员'), ('NUTRITIONIST', '营养师'), ('REHAB', '康复师'), ('PSYCH', '心理支持'), ('SUPERVISOR', '服务主管')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', '执行中'), ('CONSULTATION', '会商中'), ('CLOSED', '已结案')], default='ACTIVE', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother', models.ForeignKey(limit_choices_to={'role': 'MOTHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('NURSING', '护理'), ('NUTRITION', '营养'), ('REHAB', '康复'), ('PSYCH', '心理支持')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('optional', models.BooleanField(default=False, help_text='是否为产妇可选择事项')),
                ('status', models.CharField(choices=[('SCHEDULED', '已排定'), ('PAUSED', '已暂停'), ('COMPLETED', '已完成'), ('REFUSED', '产妇拒绝')], default='SCHEDULED', max_length=20)),
                ('pause_reason', models.TextField(blank=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='care.careplan')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='care.careplan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='care.planitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('NURSING', '护理'), ('NUTRITION', '营养'), ('REHAB', '康复'), ('PSYCH', '心理支持')], max_length=20)),
                ('kind', models.CharField(choices=[('ASSESSMENT', '评估'), ('RECOMMENDATION', '建议'), ('CONTRAINDICATION', '禁忌'), ('FEEDBACK', '执行反馈')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('SUPERSEDED', '已被取代'), ('WITHDRAWN', '已撤回')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opinions', to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='opinions', to='care.planitem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='care.careplan')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='care.professionalopinion')),
            ],
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('items_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='care.careplan')),
                ('opinions', models.ManyToManyField(related_name='bound_versions', to='care.professionalopinion')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ItemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', '创建项目'), ('PAUSED', '暂停'), ('RESUMED', '恢复'), ('COMPLETED', '完成'), ('REFUSED', '产妇拒绝'), ('REFUSAL_REVOKED', '撤销拒绝')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='care.careplan')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='care.planitem')),
                ('opinion', models.ForeignKey(blank=True, help_text='本次变更依据的专业意见', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_events', to='care.professionalopinion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', '待会商'), ('RESOLVED', '已解决')], default='OPEN', max_length=20)),
                ('summary', models.TextField(help_text='矛盾点描述')),
                ('pending_decisions', models.JSONField(default=list, help_text='尚缺的决定，如 [{"key": "...", "question": "...", "needed_from": ["NURSING"]}]')),
                ('decisions', models.JSONField(blank=True, default=list, help_text='会商时对每项待决事项给出的结论')),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='care.careplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_consultations', to=settings.AUTH_USER_MODEL)),
                ('opinions', models.ManyToManyField(related_name='consultations', to='care.professionalopinion')),
            ],
        ),
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('THIS_OCCURRENCE', '仅本次'), ('TODAY', '今日内'), ('ITEM', '该项目全部')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refusals', to='care.planitem')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refusals', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refusals', to='care.careplan')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_refusals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='careplan',
            constraint=models.UniqueConstraint(fields=('mother', 'date'), name='uniq_plan_per_mother_day'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'number'), name='uniq_version_number'),
        ),
    ]
